name: Playwright Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.51.1  # Use the latest version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mark repository as safe for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test validation/playwright || true # Continue even if error
      
      - name: Generate README Update
        run: node validation/update-readme-loading.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update loading test results in README" || exit 0
          git push

